"""Embed lighting_GF/FF.json + walls_GF/FF.svg into lighting_data.js so index.html works from file:// (no server)."""
import json, os
_H = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else HERE
_emb = {}
for _fl in ("GF", "FF"):
    _jp, _sp = os.path.join(_H, f"lighting_{_fl}.json"), os.path.join(_H, f"walls_{_fl}.svg")
    if os.path.exists(_jp) and os.path.exists(_sp):
        _emb[_fl] = dict(json=json.load(open(_jp, encoding="utf-8")), svg=open(_sp, encoding="utf-8").read())
open(os.path.join(_H, "lighting_data.js"), "w", encoding="utf-8").write(
    "// generated by build_data_js.py from lighting_GF/FF.json + walls_GF/FF.svg\nwindow.LIGHTING_DEFAULT = " + json.dumps(_emb, ensure_ascii=False) + ";\n")
print("lighting_data.js:", list(_emb))
